owner: TetraGG
repo: Upptime
assignees: TetraGG

sites:
  #  - name: Internet Access
  #     url: https://tetragg.com
  #    icon: https://www.pngkey.com/png/full/45-455131_white-internet-icon-png-clipart-library-library-internet.png
  #    method: GET
  #    expectedStatusCodes:
  #      - 200
  #      - 201
  #      - 404
  - name: Proxy
    url: https://proxy.tetragg.com
    icon: https://github.com/traefik/traefik/blob/master/webui/src/statics/icons/favicon.ico
    method: GET
    headers:
      - "Authorization: Basic $BASIC_AUTH_TOKEN"
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200
  - name: Proxmox
    url: https://pve.tetragg.com
    icon: https://www.proxmox.com/templates/yoo_nano2/favicon.ico
    method: GET
  - name: Jellyfin
    url: https://jellyfin.tetragg.com
    icon: https://jellyfin.org/favicon.ico
    method: GET
  - name: Nextcloud
    url: https://nextcloud.tetragg.com
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png
    method: GET
status-website:
  name: TetraGG
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: status.tetragg.com
  theme: night
  introTitle: "**TetraGG** domain uptime monitor and status page"
  introMessage: "This page permits to follow in real-time the accessibility of TetraGG domains and provided services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
