owner: TetraGG
repo: Upptime

sites:
  - name: Internet Access
    url: https://tetragg.com
    icon: https://toppng.com/uploads/preview/book-internet-icon-white-11562892132afi42kloxz.png
    assignees: TetraGG
  - name: Jellyfin
    url: https://jellyfin.tetragg.com
    icon: https://jellyfin.org/favicon.ico
    method: POST
    assignees: TetraGG
  - name: Nextcloud
    url: https://nextcloud.tetragg.com
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png
    method: POST
    assignees: TetraGG
    
status-website:
  name: TetraGG
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: status.tetragg.com
  theme: night
  introTitle: "**TetraGG** domain uptime monitor and status page"
  introMessage: "This page permits to follow in real-time the accessibility of TetraGG domains and provided services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO