owner: TetraGG
repo: Upptime

sites:
  - name: Internet Access
    url: https://tetragg.com
    icon: https://www.pngkey.com/png/full/45-455131_white-internet-icon-png-clipart-library-library-internet.png
    assignees: TetraGG
  - name: Proxmox
    url: $PROXMOX_URL
    icon: https://www.proxmox.com/templates/yoo_nano2/favicon.ico
    method: GET
    assignees: TetraGG
  - name: Gitlab
    url: https://gitlab.tetragg.com
    icon: https://gitlab.com/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png
    method: GET
    assignees: TetraGG
  - name: Jellyfin
    url: https://jellyfin.tetragg.com
    icon: https://jellyfin.org/favicon.ico
    method: GET
    assignees: TetraGG
  - name: Nextcloud
    url: https://nextcloud.tetragg.com
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png
    method: GET
    assignees: TetraGG

status-website:
  name: TetraGG
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: status.tetragg.com
  theme: night
  introTitle: "**TetraGG** domain uptime monitor and status page"
  introMessage: "This page permits to follow in real-time the accessibility of TetraGG domains and provided services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO